name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: paolino/dev-assets/setup-nix@v0.0.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build and run tests
        run: |
          nix build .#unit-tests --quiet
          ./result/bin/unit-tests

      - name: Build and run offchain tests
        run: |
          nix build .#offchain-tests --quiet
          ./result/bin/offchain-tests

      - name: Build offchain interfaces
        run: nix build .#cardano-mpfs-offchain --quiet

      - name: Check formatting
        run: |
          nix develop --quiet -c fourmolu -m check $(find . -name '*.hs' -not -path './dist-newstyle/*' -not -path './.direnv/*')
          nix develop --quiet -c bash -c "find . -name '*.cabal' -not -path './dist-newstyle/*' | xargs cabal-fmt -c"

      - name: Lint
        run: nix develop --quiet -c hlint $(find . -name '*.hs' -not -path './dist-newstyle/*' -not -path './.direnv/*')
